---
title: "Untitled"
author: "Sahithi Polisetty"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
absent <-read.csv("Absenteeism_at_work2.csv")
str(absent)
```

```{r}
##Converting into factors
#absent$ï..ID<- as.factor(absent$ï..ID)
absent$Reason.for.absence <- as.factor(absent$Reason.for.absence)
absent$Month.of.absence <- as.factor(absent$Month.of.absence)
absent$Day.of.the.week <- as.factor(absent$Day.of.the.week)
absent$Seasons <- as.factor(absent$Season)
absent$Disciplinary.failure <-as.factor(absent$Disciplinary.failure)
absent$Education <- as.factor(absent$Education)
absent$Social.drinker <-as.factor(absent$Social.drinker)
absent$Social.smoker <-as.factor(absent$Social.smoker)
absent$ï..ID  <- NULL
absent$Work.load.Average.day<-as.numeric(absent$Work.load.Average.day)
absent$Month.of.absence<- NULL
absent$Weight<- NULL
absent$is_Thur<-ifelse(absent$Day.of.the.week==5,1,0)
absent$Day.of.the.week<-NULL
absent$Seasons<-NULL
#absent$is_Educ3<-if_else(absent$Education==3,1,0) Once I do this, Seasons and Education3 no longer significant
#absent$Education<-NULL
absent$Transportation.expense<-NULL
absent$Social.drinker<-NULL
absent$Disciplinary.failure<-NULL
absent$timecat <- absent$Absenteeism.time.in.hours
absent$timecat <- ifelse(absent$timecat == 0, "Not Absent", ifelse (absent$timecat>0 & absent$timecat<8, "<1 day", ifelse(absent$timecat>=8 & absent$timecat<=32, "1-4 days", ifelse(absent$timecat>32 & absent$timecat<=56, "1 week", ifelse(absent$timecat>56 & absent$timecat<=96, "2 weeks", "3 weeks")))))
          
absent$timecat <- as.factor(absent$timecat)
```

```{r}
n <- nrow(absent)  # Number of observations
ntrain <- round(n*0.75)  # 75% for training set
set.seed(314)    # Set seed for reproducible results
tindex <- sample(n, ntrain)   # Create a random index
train_absent <- absent[tindex,]   # Create training set
test_absent <- absent[-tindex,]   # Create test set

## Construct SVM Model
library(e1071)
svm1 <- svm(timecat~., data=absent, 
          method="C-classification", kernal="vanilladot", 
          gamma=0.1, cost=10)
summary(svm1)
```
```{r}
## Making Predictions
prediction <- predict(svm1, test_absent)

## Display confusion matrix
library(caret)
xtab <- confusionMatrix(as.factor(test_absent$timecat), as.factor(prediction))
xtab
```

